apiVersion: apps/v1
kind: Deployment
metadata:
  name: exposer-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exposer-controller
  template:
    metadata:
      labels:
        app: exposer-controller
    spec:
      serviceAccountName: exposer-controller
      containers:
      - name: controller
        image: exposer-controller:local